# Site settings
title: "Kewth's blog" # 你的博客名字，可以定义修订
header-img: "HY_zly.jpg"
tagline: "cn"  
description: "This is a blog to say hello world."  # 一句话描述你的博客
baseurl: "" # 地址?
url: "http://kewth.github.io"  # 此处填写你的博客地址 
gems: [jekyll-paginate] # 预览

# About/contact
owner: 
  name: "Kewth" # 填写作者信息：名字
  email: "wthdsg@foxmail.com" # 填写作者信息：邮箱
  bio: "Hello world!!" # 填写作者信息：博客描述

# Data
gavatar: https://kewth.github.io/img/favicon.png # 浏览器地址栏小图标，可自定义更改
favicon: https://kewth.github.io/img/favicon.png # 浏览器地址栏小图标，可自定义更改

douban_username:  # 你的豆瓣id
twitter_username: 
github_username: Kewth 
facebook_username: 
weibo_username: 
zhihu_username: 
luogu_usernameid: 52232
livere_uid: Kewth # 来必力ID

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: redcarpet
redcarpet:
    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
# markdown: rdiscount
# markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
paginate_path: "page:num"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Changsha

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Kewth" # 你的名字
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  duoshuo :
    short_name :  # 填写你的 disqus id
  disqus :
      short_name :  # 填写你的 disqus id

# Analytics and webmaster tools stuff goes here
google_analytics:  # 填写你  google_analytics id
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
# NULL
